version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com/web-container-project-ecr:latest

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t 123456789012.dkr.ecr.us-east-1.amazonaws.com/web-container-project-ecr:latest .

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/web-container-project-ecr:latest
      
      # Generate imagedefinitions.json file
      - printf '[{"name":"web-container","imageUri":"%s"}]' "123456789012.dkr.ecr.us-east-1.amazonaws.com/web-container-project-ecr:latest" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
